### ISSUE TITLE
dashboard: sidebar menu

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#2554]
* [x] deselect icon after click
* [x] change gyphicons to fontawesome icons
* [x] on MVC pages the toggle is reversed after page load #2596 
* [x] support default theme #2555
* [x] wrong colours in default theme #2601
* [x] save preference in local session (people will complain if it's not sticky)
* [x] footer gap on minified view #2626 
* [x] toggle disappears (in Chrome) when developer tools are open -- due to height requirement, fix resize back to original preference #2628
* [x] delay / click behaviour (hover should probably trigger menu instantly) #2727
* [x] tooltips for full/minified button toggle #2742
* [x] presentation: scrap transparency in the overlay #2755
* [x] proportions: logos vs. submenus is too drastic
* [x] remove expansion delay / animation
* [x] hover in and out resets same elements instead of reopening them
* [x] sticky sub-submenu on mouseout when next item does not have a sub-submenu #2782
* [x] positioning of submenu may be cropped due to small height #2865

**Comment by marjohn56** [comment]
Default theme #2555

**Comment by opnsenseuser** [comment]
@franco font-size, color, (no transparent) and hover modification!

https://github.com/opnsense/core/pull/2709

**Comment by opnsenseuser** [comment]
@franco .js update 
https://github.com/opnsense/core/pull/2724

**Comment by opnsenseuser** [comment]
@franco tooltip for sidebar
https://github.com/opnsense/core/pull/2742

**Comment by fichtner** [comment]
@opnsenseuser thanks, I'll merge this over the weekend when I have a clear head for this :)

**Comment by opnsenseuser** [comment]
@franco great thx. Please its also Important to merge all Themse. Like opnsense, cicada, tukan and the dark theme. All pr‘s are already done! Thx , regards rene

**Comment by opnsenseuser** [comment]
@franco have now cleaned up both themes (tukan and cicada) completely and as Martin all tokenize2 and nv.d3 - css stuff divided into seperate files. besides, I've tried correcting all tabs and wrong spaces. It took a lot of effort, but I wanted to make fabian a pleasure. He was right, but I had no time for it so far. Greetings René... hope you can merge it soon!!! thx - nice day!!

**Comment by fichtner** [comment]
@opnsenseuser almost done :)

What do you think about 14px for the menu font? I'm also pondering about the click behaviour that undoes the "transition" effect. If we had it open instantly the click to remove would feel more natural. Right now it opens and habit clicks which makes the opening menu disappear again.

What do you think?

**Comment by opnsenseuser** [comment]
@franco 

the font-size on 14px is okay. the problem is the submenu. 
if it is too high it would be outside the viewports. 
Then you could only do it as the dropdown menus work -> go up if there is not enough space. 
If there was no space here then we would face a problem. 
Freenas simply added a scroll bar to each submenu and set the height of the submenu to a fixed value.
I think that's not very user friendly and looks very strange.

It is not easy to find a really good solution. 
In any case, we already have a very good starting point on which we can build.
I have to think about it.

Interesting would be the opinion of Fabian or others. Ideas are always good.

**Comment by opnsenseuser** [comment]
@fichtner 
I do not know if that is possible but would be very interesting to do a survey. and everyone who tests the sidebar to ask what bothers them or what they would like. I do not know if that's possible. I always find the other's feedback very interesting!

**Comment by fichtner** [comment]
sure, you can make a survey for the plugin theme users (cicada, rebellion, tukan). we'll release the current state for those in 18.7.4. the default theme needs some extra care for compatibility testing later on, but there's time for that.

**Comment by opnsenseuser** [comment]
@fichtner Because of your second question I wanted to ask you again. 
Did I understand correctly that you can imagine with one click the submenu to close?
So the click event should be limited to running menu items and closing the submenu? Is this correct?

**Comment by fichtner** [comment]
@opnsenseuser the clicks work fine, but when it's still expanding on hover and you click it removes the opening menu

**Comment by opnsenseuser** [comment]
@fichtner ok. I'll take a look. :-)

**Comment by opnsenseuser** [comment]
@fichtner ok, you a right. we wait one or two days!!
In the mean time i start working on the click behavior for sidebar!

regards, rené

**Comment by fichtner** [comment]
take a break, let it sink in, enjoy the evening. :)

cheers,
Franco

**Comment by opnsenseuser** [comment]
👍

**Comment by marjohn56** [comment]
Very busy with real work for the next few months as I’ve had some very large projects pushed in my direction, so I have very little time to play with OPNsense. Can you send me an image of what the changes look like?

**Comment by opnsenseuser** [comment]
@marjohn56 

icons are smaller (28px to 20px now)
font-size larger (12px to 14px now)

What do you think?

Cicada:
![grafik](https://user-images.githubusercontent.com/34602360/46021792-aef0ee80-c0e1-11e8-9634-66fed2b76d9f.png)

Opnsense:
![grafik](https://user-images.githubusercontent.com/34602360/46021971-0abb7780-c0e2-11e8-9822-68d39e8cc641.png)

**Comment by opnsenseuser** [comment]
@marjohn56 I like it-> It also fits better to the original navigation!

what do you think?

**Comment by marjohn56** [comment]
Graphical look has never been my speciality, ask some of my work colleagues. :)

I'd go with the second series, 13 point I think you said.

**Comment by fichtner** [comment]
cicada and tukan are now 13px for 18.7.4. we'll keep the default theme at 14px for now. entirely unsure... :)

**Comment by opnsenseuser** [comment]
@fichtner 👍

**Comment by opnsenseuser** [comment]
@fichtner we should find a common denominator up to version 19.1. but there is still time.

**Comment by opnsenseuser** [comment]
@fichtner 
@marjohn56 for Tukan and Cicada i set the font-size to 13px, for better reading experience and fixed the padding a little. it´s on you if you deside to choose 14px or 13px. the org theme is set to 14px. noone is shure whats the better option!
if it´s not to late, I would modify the dark theme for you if you want to change something and do a pr.

**Comment by opnsenseuser** [comment]
@fichtner thats impossible for me. I get back from work in 8 Hours.
@marjohn56

**Comment by fichtner** [comment]
no worries, there's always 18.7.5

**Comment by opnsenseuser** [comment]
@fichtner I almost forgot that ;-)

**Comment by opnsenseuser** [comment]
Also freenas is currently not perfect (beta3), but also on a good way. 
I'm posting this just to have a little input and maybe more ideas to develop. 

best regards rené

![grafik](https://user-images.githubusercontent.com/34602360/46168914-09cd4600-c29a-11e8-9fcf-018656cf7cba.png)

**Comment by fichtner** [comment]
@opnsenseuser surprise, all your patches landed in 18.7.4 since I had to redo the build partially :)

I wanted to solve the positioning so that it goes up instead of down to avoid as much cropping as possible but I've not yet understood the JS magic involved.

**Comment by opnsenseuser** [comment]
@fichtner you are the best. I wanted to thank you anyway, but I'm also in the process of making some improvements at the sidebar.

"but I have not understood the JS magic involved." -> I would be very surprised if you did not understand that. Or the sidebar is so poorly "programmed" by me, that it does not understand a proper programmer. I can not explain that otherwise!

**Comment by mimugmail** [comment]
@opnsenseuser @marjohn56

I'm on OPNsense 19.1.a_288-amd64 using Sidebar with default theme and I'm getting into scaling issues with long lists. See screenshot where Services get's cut off.

Also, my mouse hovers over "Nut", but the sub-menu open is from Nginx. Everytime where the next below entry does not have a sub-menu, it sticks with the one above.

![image](https://user-images.githubusercontent.com/20438689/46205971-d84c8d00-c322-11e8-952e-edcd95ad2e14.png)

**Comment by opnsenseuser** [comment]
@mimugmail I have already talked to franco about it some time ago. the idea would be to do it as with the dropdown menus. so there is not enough space down the menu should go up. the only question remains ... What do we do if there is not enough space up there?

**Comment by opnsenseuser** [comment]
@mimugmail 
@fichtner 
@marjohn56 
That's why I decided to leave the font size of the sidebar at 13px. so that the legibility is right and you have more space upstairs.

**Comment by opnsenseuser** [comment]
@mimugmail 
@fichtner 
@marjohn56 
we would have to try all possibilities once. The last resort is of course the simplest though visually and usability technically the worst -> we build a scrollbar.
freenas did that too. But as already written is not easy to use and looks very strange. html5 and css3 but can overwrite the color of the scrollbar, which went before html5 and css3 only with javascript. -> at least, but still not nice!

**Comment by fichtner** [comment]
@opnsenseuser this looks light the right direction. 

Let's go back to the drawing board for a second to consider design choices. There are a couple of methods to resolve the cropped situation:

1. fixed max height containers with scroll bar
2. multi-column layout if not enough space
3. expand upwards
4. More ideas for this list?

I personally don't like the scroll bar approach and wouldn't mind a combination of several other approaches that allows for "one click" navigation with the sidebar with ideally a straight horizontal movement in the best case. What do you think?

**Comment by opnsenseuser** [comment]
@franco I do not quite understand you. would you like a general remodeling? So, all submenus open horizontally? it would be easier for me if you could give me a very simple draft in the form of a simple sketch. very simple. just so I can empathize your imagination better. best regards, rene

**Comment by franco** [comment]
@opnsenseuser: @franco != @fichtner. Thanks!

**Comment by opnsenseuser** [comment]
> @opnsenseuser: @franco != @fichtner. Thanks


that happens to me now all the time. I'm sorry.

**Comment by fichtner** [comment]
No, just trying to push what we have to the next level... best case horizontal menu navigation:

<img width="428" alt="screen shot 2018-09-28 at 9 05 42 pm" src="https://user-images.githubusercontent.com/1915288/46228620-e9b58980-c362-11e8-89ee-0ace288d4016.png">

move cropped menu up by detecting end of screen:

<img width="229" alt="screen shot 2018-09-28 at 9 06 17 pm" src="https://user-images.githubusercontent.com/1915288/46228655-0487fe00-c363-11e8-8c99-9c029a5ebb90.png">

**Comment by opnsenseuser** [comment]
@fichtner ok, so you mean, if the submenu is too long then should the submenu open to the right?

**Comment by opnsenseuser** [comment]
@fichtner fix for "hover in and out resets same elements instead of reopening them"
https://github.com/opnsense/core/pull/2770/commits/e8dad84793c2f998a0b1ade118fb10b266168eca

**Comment by opnsenseuser** [comment]
@mimugmail
@fichtner 

If the "routing" entry is copied to the main menu "master" as shown by @mimugmail, the space upwards should be sufficient for a submenu to open up if there is not enough space left. will the "routing" entry be taken over in the master?

**Comment by opnsenseuser** [comment]
@fichtner 
@mimugmail 
I also think that 13px is sufficient for the font size in the sidebar. It's hardly a difference, but it gives you a lot of space!

**Comment by mimugmail** [comment]
@opnsenseuser the routing menu is only displayed when you install plugin FRR. You easily install it to test against. I dont remember the discussion why we put it in main and not under services.

**Comment by fichtner** [comment]
I don't know about the routing menu yet. I'd wish it became a standard, but that requires more work and lobbying from my side. Hopefully have it all worked out for 19.1.

**Comment by mimugmail** [comment]
When downloading a backup of the configuration it does not minimize (latest master)

**Comment by opnsenseuser** [comment]
@mimugmail 
@fichtner 
I think we need you unfortunately!

**Comment by fichtner** [comment]
I tried reproducing. Which browser is this? What steps?

**Comment by mimugmail** [comment]
Franco keeps it rolling :)
https://github.com/opnsense/tools/commits/master

**Comment by fichtner** [comment]
@opnsenseuser @mimugmail yes, when 18.7.5 is released we have a working src.git master branch for 19.1, but I'm not sure how we will do a public beta test yet.

**Comment by fichtner** [comment]
@opnsenseuser I'll be issuing images based on 18.7.5 with the newer 19.1-BETA operating system update so you can do a clean install. But it takes 18.7.5 to get there. :)

**Comment by opnsenseuser** [comment]
@fichtner 
thanks franco. That's a great news!
 I think there are some opnsense users who are already waiting to test this. 
ingenious!. 
just one thing. In opnsense theme i still have found a small error in the sidebar Navigation css that I will then quickly register tomorrow on github. Thats just for your Information.

Thx,
Regards
Rene

**Comment by fabianfrz** [comment]
I am not sure if this is already fixed but it opens the wrong submenu on hover:
![grafik](https://user-images.githubusercontent.com/3713914/46821912-516bcb80-cd8a-11e8-8f4f-8f68c20c6935.png)

**Comment by opnsenseuser** [comment]
@fabianfrz Everything works as it should for me. 
What do you click and what happens then? 
I only use the click function and that does not do anything else than I would click on the element with the mouse.

**Comment by fabianfrz** [comment]
Clicking works as expected but hover does not.

**Comment by opnsenseuser** [comment]
@fichtner 
@fabianfrz 
Everything works without problems for me. maybe franco can detect something.

**Comment by opnsenseuser** [comment]
@marjohn56 
can you confirm that Martin?

**Comment by marjohn56** [comment]
Hold on I'll need to bring my test system up to date.

**Comment by marjohn56** [comment]
I have just done a code-core etc and it all looks fine to me, the correct sub menus are opening as expected.

[menus.zip](https://github.com/opnsense/core/files/2470712/menus.zip)

Not the best capture in the world but it proves a point. ;->

**Comment by opnsenseuser** [comment]
@marjohn56 Thanks Martin for your support. I also could not find anything. everything perfect so far

**Comment by opnsenseuser** [comment]
@fabianfrz ok, that was a valuable note. I'll take a look.

do you have the chance to test it under debian or other distributions? That would be great. thanks, best regards, rene

**Comment by fichtner** [comment]
> I am not sure **if this is already fixed** but it **opens the wrong submenu on hover**:

I'm sorry to say that without stating which version you are running this report is totally useless. :)

**Comment by mimugmail** [comment]
I can test Debian, elementaryOS and Ubuntu later today. But they are all Debian based :)

**Comment by opnsenseuser** [comment]
@mimugmail thx for your Support!

**Comment by mimugmail** [comment]
It works for me in elementaryOS under Firefox 62, Chromium 69 and Epiphany 3.8.11.
But with all I have a cropped menu in Services (and this time it's 24 inch display) .. see screenshot

![screenshot from 2018-10-12 08-35-22](https://user-images.githubusercontent.com/20438689/46852206-7ac44000-cdfa-11e8-9834-c8fd4b7895a3.png)

**Comment by opnsenseuser** [comment]
@mimugmail the cropped menu is still under developement!
see -> 





![todolist](https://user-images.githubusercontent.com/34602360/46854766-32a91b80-ce02-11e8-8e34-41aabc5050b4.png)

**Comment by mimugmail** [comment]
Ah, good to see you're still on it. I don't read every commit, but happy to help where I can 👍

**Comment by opnsenseuser** [comment]
you helped me a lot with your test. 👍 
If you could still test debian I would be very grateful. 
best regards rené

**Comment by mimugmail** [comment]
Sure, Debian 7, FF 52.8 works

**Comment by opnsenseuser** [comment]
And Suse and Redhat will be tested by me later on. Have a lot of work to do today. (real work)!

**Comment by fabianfrz** [comment]
@opnsenseuser you don't need to test manjaro - that is Arch Linux based where we currently have 62.0.2 (64-Bit)

CentOS 7: the bug is reproducable:
![screenshot_20181012_194240](https://user-images.githubusercontent.com/3713914/46885013-fb188e80-ce56-11e8-9efd-9f954fdb38ee.png)

Also here clicking works. Firefox 52.7.0 ESR

**Comment by fichtner** [comment]
Which OPNsense version? I'll just keep asking. ;)

**Comment by fabianfrz** [comment]
good point was 18.7.2 - on OPNsense 19.1.a_288-amd64 everything is fine. Arch Linux and CentOS 7.

**Comment by fichtner** [comment]
@opnsenseuser ok, thanks for all your work on this. the sidebar has come a really long way thanks to you! :)

I removed the border addition https://github.com/opnsense/core/commit/724f41dad as it does not fit the current main theme in the menu which doesn't use separators when collapsed. I only noticed this morning. Sorry for not noticing it earlier.

**Comment by opnsenseuser** [comment]
> 
> 
> @opnsenseuser I'll be issuing images based on 18.7.5 with the newer 19.1-BETA operating system update so you can do a clean install. But it takes 18.7.5 to get there. :)

@fichtner 
hi franco, 
18.7.5 works great. please, can you tell where i can download 18.7.5 with the included 19.1. beta for testing the denverton intel as you told me?

regards rené

**Comment by fichtner** [comment]
I'll send the link privately via mail in a second

**Comment by opnsenseuser** [comment]
@fichtner 
thx, i already tried that one.
but it ends up with "Enter full pathname of shell or RETURN for /bin/sh

![grafik](https://user-images.githubusercontent.com/34602360/47109999-02250f80-d250-11e8-8151-dd13d6cf7cda.png)

**Comment by fichtner** [comment]
awkwardly strange, which image type is this?

**Comment by opnsenseuser** [comment]
OPNsense-19.1.b-OpenSSL-vga-amd64.img

 

Von: Franco Fichtner <notifications@github.com> 
Gesendet: Mittwoch, 17. Oktober 2018 21:31
An: opnsense/core <core@noreply.github.com>
Cc: René <rene@team-rebellion.net>; Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/core] dashboard: sidebar menu (#2554)

 

awkwardly strange, which image type is this?

**Comment by fichtner** [comment]
@AdSchellevis is this because of https://github.com/opnsense/core/commit/2d360a391b ?

**Comment by AdSchellevis** [comment]
@fichtner not very likely, I don't see how, but if there's a reproducible scenario using something I can boot in a vm, I can check.

**Comment by opnsenseuser** [comment]
**positioning of submenu may be cropped due to small height:**
https://github.com/opnsense/core/pull/2864

**Comment by opnsenseuser** [comment]
once again!
positioning of submenu may be cropped due to small height!
https://github.com/opnsense/core/pull/2865

**Comment by fichtner** [comment]
@AdSchellevis @mimugmail the last fix went in via @opnsenseuser  -- what do you think?

It could still be too small in the worst case, but I do think this ready for general release (it's disabled in the plugin themes already). The choice is not to use it if space is too small.... ;)

**Comment by AdSchellevis** [comment]
@fichtner I'll have to check, also for backwards compatibility if these additions aren't installed. Let me get back on this.

**Comment by fichtner** [comment]
no rush, 19.1 for default theme is also fine IMO

**Comment by opnsenseuser** [comment]
I agree. Gives us more time to test and optimize!

**Comment by mimugmail** [comment]
Installed latest master .. when I hover from Services to Web Proxy and then go up, the Administratio and Logging sub menu stays.

**Comment by mimugmail** [comment]
Screenshot enclosed .. sub menu of Unbound behind Web Proxy, also the list it cut off at the top now instead of below.

![image](https://user-images.githubusercontent.com/20438689/47901251-b1ccc500-de7f-11e8-9765-c866d8991d91.png)

**Comment by fichtner** [comment]
indeed, that bug seems to be back. thanks for spotting it :) expand up is ok, though?

**Comment by opnsenseuser** [comment]
I can only Test in the evening.

**Comment by opnsenseuser** [comment]
Could be old bug Problem or Cache (Firewall,Browser) and so on....

**Comment by opnsenseuser** [comment]
I know that it should work. Tested it on all themes

**Comment by opnsenseuser** [comment]
@fichtner 
@mimugmail 
yes, unfortunately .... you have too many elements, the space is not enough. Some things can be solved, but some unfortunately not. I think we can not avoid the scrollbar!
![grafik](https://user-images.githubusercontent.com/34602360/47916378-52ce7680-dea6-11e8-938a-dc7e8230f90d.png)


maybe the solution in such a case would be to downsize the font. This would also reduce the div levels.
whether one can dazzle the submenu above the header, I must first determine. Since we work here partially with fixed positions, it seems to be difficult.

z-index description:
Items can have only one z-index if they have an item of position that differs from static or if they are flex-items

**Comment by opnsenseuser** [comment]
one can also consider, if the div is too long to switch back to the standard navigation!

**Comment by opnsenseuser** [comment]
@franco have you tested it?

**Comment by opnsenseuser** [comment]
@fichtner 
@mimugmail 
solution:
![grafik](https://user-images.githubusercontent.com/34602360/47949026-56144180-df3c-11e8-863b-9736b7862600.png)

**Comment by mimugmail** [comment]
If you want me to test just tell me your repo/branch :)

**Comment by opnsenseuser** [comment]
@fichtner 
@mimugmail 

opnsense theme mod (cut off problem fix)
https://github.com/opnsense/core/pull/2869

tukan cicada theme mod (cut off problem fix)
https://github.com/opnsense/plugins/pull/953

**Comment by opnsenseuser** [comment]
@mimugmail would be great if you could test this! regards rené

**Comment by opnsenseuser** [comment]
@fichtner 
@mimugmail 
https://github.com/opnsense/core/pull/2872

**Comment by opnsenseuser** [comment]
i´m really proud of the last mods i did for sidbar and all themes. it looks and feels much much better now
![grafik](https://user-images.githubusercontent.com/34602360/47961783-b4f7ba80-e011-11e8-8d19-79b0c0249cd1.png)

**Comment by opnsenseuser** [comment]
I hope to see the mods at least for tukan and cicada in the next release. Thank you, best regards, René

**Comment by fichtner** [comment]
yes, no worries, this is great work. just turns out to be very difficult to make it perfect 👍

**Comment by fabianfrz** [comment]
@fichtner the todo list is completed. Close?

**Comment by opnsenseuser** [comment]
👍

**Comment by fichtner** [comment]
ok, sure, thanks everyone ❤️

**Comment by opnsenseuser** [comment]
As I completed my first project with today's final public relations sidebar (https://github.com/opnsense/core/pull/2877), I'm looking for a new challenge.
You may now know about my level of knowledge.
I would be very happy about every new task. There is still much to do and I am full of energy.

Thanks again for your support in all matters!

René

**Comment by fabianfrz** [comment]
@opnsenseuser if you don't have an idea what you can improve, you can work on the docs as well. Users often ask for a chapter about the firewall section for example.

**Comment by opnsenseuser** [comment]
> 
> 
> There's one small bug that I see if you install "vnstat" plugin. In the service menu, go to "web proxy", then move mouse up to "vnstat". "web proxy" is still extended and not closed. The other way around into "vnstat" seems to do that correctly for "unbound dns".

fix -> https://github.com/opnsense/core/pull/2877
