### ISSUE TITLE
OPNsense 20.7 beta todo

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#3969]
This is a tracking ticket for things todo before releasing our public 20.7 beta and contains scope, goals and attention points we have collected.

- [x] Fix syslogd clog output (https://github.com/opnsense/ports/commit/ce9cb826c4218cf1aec5d2954d4ce3033c277527)
- [x] Filter live log and new log filterlog output (https://github.com/opnsense/core/commit/599e17af763a0ab2d20f3a1b488aced36c6edf99)
- [x] Filter log overview and new filterlog output (https://github.com/opnsense/core/commit/67c0d0dcfdb80399a316eae4b4c3ebc898e2707c)
- [x] replace boot loader artwork (alpha booting with HardenedBSD artwork)
- [x] handle new `net.pf.request_maxcount` (https://reviews.freebsd.org/D18909) either add sensible error/warning messages or choose a new default for our usage. The new system default is 64k
- [x] create opnsense-update (https://github.com/opnsense/update) version (branch repo?) 
- [x] add signing keys
- [x] prepare mirror for 20.7
- [x] Publish amd64+OpenSSL packages
- [x] test netmap support with Suricata 
- [x] patch HBSD 12.1 with ipfw dummy net hook and validate functionality
- [x] patch HBSD 12.1 with shared-forwarding and validate functionality
- [x] Kernel / base refresh after recent FreeBSD SA
- [x] Refresh packages set (amd64 + OpenSSL only)
- [x] radvd crashing hard without any visible error message
- [x] Build dvd image (amd64 + OpenSSL only)
- [x] Build serial image (amd64 + OpenSSL only)

**Comment by fichtner** [comment]
:)
