### ISSUE TITLE
Syslog - remove clog support in 22.1

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/core#5337]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

Currently we do support two different syslog systems for historic reasons, which given nowadays equipment seems to be less relevant anymore. Clog offers rotating logfiles, which could save log space on embedded systems, but often is misconfigured (setup large target slowing down log handling a lot) or just unneeded ([mem]disk space is less of an issue)

**Describe the solution you like**

Remove clog support, explain the correct usage of our logging (https://github.com/opnsense/docs/issues/357) and stick to a single log system and format.

**Describe alternatives you considered**

keeping clog around, which seems to be less logical.

**Additional context**

none

**Comment by fichtner** [comment]
TODO/Questions:

- [ ] prefixes.php needs a fix for new log format or maybe even a rewrite
- [ ] core.inc references "syslogd" service
- [ ] rename system_syslogd_* to system_syslog_* and/or try to migrate that cruft to rc files
- [ ] diag_logs_settings.php calls killbyname('syslogd');
- [ ] remove async flag from system_syslogd_start()

**Comment by kulikov-a** [comment]
hi!
Considering the upcoming changes and RFC 5424 migration, how silly is the idea to change the System: Log Files: General page a little bit more? change severity filter to something like "maximum severity" (single select) and make it "Warning" by default (and may be storing filter value in localStorage)?
(inspired by https://forum.opnsense.org/index.php?topic=25676.0 (apart from manners))

thanks!

**Comment by AdSchellevis** [comment]
@kulikov-a I'm open for suggestions, I do expect some messages in core will use a wrong level at the moment by the way, but that will sort itself out eventually.

**Comment by kulikov-a** [comment]
@AdSchellevis thanks! then I'll try to play with it and make a pr for discussion if something useful comes out
