### ISSUE TITLE
interfaces: move WireGuard kernel plugin to core

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6827]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

WireGuard kernel plugin was rewritten to use native tooling so we can get rid of wireguard-tools package (and its bash dependency). Also FreeBBSD 13.2 has its own kernel module so we can even lose the dependency on wireguard-kmod package.

**Describe the solution you like**

* [x] WireGuard can now live as a core VPN service.
* [x] Remove both plugins (Go and Kernel) from plugins.git master branch as well once it hits core (setting PLUGIN_OBSOLETE=yes)
* [x] Rename Local -> Instances and Endpoints -> Peers (excluding the peers:endpoints config settings)
* [x] Reenable the kernel module build in tools.git: https://github.com/opnsense/tools/commit/eecf924ede for 24.1 builds
* [x] Make sure the documentation matches (https://github.com/opnsense/docs/issues/504)
* [x] Remove wireguard-kmod dependency on stable/24.1

**Describe alternatives you considered**

Nothing else now that the questionable scripting is gone.

**Additional context**

N/A
