### ISSUE TITLE
dhcrelay: migrate to MVC/API as well as OpenBSD replacement port

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#6983]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

DHCP relay is a very old component that could need a bit of refactoring and MVC and API while we are at it. Since ISC DHCP is end of life we move the the OpenBSD port which has some oddities and limitations but on a whole it seems to work fine.

Some of the issues are already described here https://github.com/opnsense/core/issues/6949

**Describe the solution you like**

Bring the settings into a model and make a new GUI/API. Restructure for OpenBSD dhcrelay oddities and fix a couple of issues along the way.

**Describe alternatives you considered**

There are other ports or we could "continue" to use our own ISC DHCP relay fork, but it's probably not worth it due to it being restrictive in terms of what services can run when.

**Comment by fichtner** [comment]
Tested basic IPv4 relay functionality: requires some form of IPv4 set on the interface igb0 to start:

    # dhcrelay -i igb0 10.0.0.1

The simplest way is to enforce a static setup as before. Static tunnels should work as well, but are harder to verify yet in practice this only works on assigned interfaces anyway and we can now see if the service starts or not. The dhcrelay hook should be later than everything else (after vpn)... if it is currently not not we may have to move it.

The limitation of dhcpd or dhcrelay no longer applies so we can split the current MVC data into separate model entries perhaps.

Still would like a more reliable test bed but that can be done when working on the MVC parts.

**Comment by fichtner** [comment]
Version 4 is done and UI and plumbing has been improved. That only really leaves version 6 to be added now.

**Comment by fichtner** [comment]
Ok some TODOs:

- [ ] Add headers to the relay and destination bootgrids
- [ ] Extract code to a new dhcrelay.inc plugin file
- [ ] Migrate IPv6 into the same model
- [ ] Add a lot of validation to make sure configuration between IPv4 and IPv6 is consistent
- [ ] Update documentation
