### ISSUE TITLE
lobby: modern dashboard replacement development

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7244]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Is your feature request related to a problem? Please describe.**

The dashboard needs a modern replacement with better sandboxing and all widgets either need to be compatible or rewritten (also the ones in plugins).

**Describe the solution you like**

Develop a secondary dashboard in the development version to try these ideas. Most likely this will remain hidden in the development version when 24.7 comes out.

Current list of work items:

_Missing functionality_

- [x] Add widget button
- [x] replace getTranslations() and api binding of canAccessEndpoints() with metadata (xml) files
- [x] ~~investigate unix domain socket connection limit.~~ socket connections seem to be no issue, instead the GUI will lock up with sufficient keep-alive connections. Cause unknown at the moment but it seems to be related to the socket open handling on the PHP side as both scaling up the lighty workers does not affect the result and the configd backend is still reachable in a locked state.
- [x] investigate themeability. Most of the styling is done properly through CSS, although there is some scripted styling to facilitate animations.

_Widgets_

- [x] System Information (static section)
- [x] CPU usage
- [x] Memory usage
- [x] Traffic Graph
- [x] Interfaces
- [x] Interface statistics
- [x] Firewall state table size
- [x] MBUF usage
- [x] SWAP usage	
- [x] Disk usage	
- [x] CARP statistics
- [x] Gateway statistics
- [x] Firewall log
- [x] Monit checks
- [ ] Static picture?
- [x] RSS feed ? (Announcements)
- [x] System log
- [x] Thermal sensors
- [x] IPsec tunnel statistics
- [ ] OpenVPN tunnel statistics
- [x] Wireguard peers
- [ ] Services
- [ ] Deciso hardware widget
- [x] ETPro telemetry

**Describe alternatives you considered**

N/A

**Additional context**

N/A

**Comment by AdSchellevis** [comment]
added progress / todo items in the ticket.

**Comment by fichtner** [comment]
@AdSchellevis the update to RC2 make the dashboard wonky for many and a nice observation was made here:

https://www.reddit.com/r/opnsense/comments/1e71y4g/comment/ldyiwxt/

> (my browser's cached copy of /ui/js/widgets/BaseWidget.js did not have the isConfigurable() function, causing all the widget rendering calls to fail.)

It appears that there is an apparent lack of cache_safe() relevant usage. I also don't know how things like this can be made cache safe when embedded into JS pages:

    import BaseWidget from "./BaseWidget.js";

**Comment by Tragen** [comment]
Our CMS does it like
`<link rel="stylesheet" type="text/css" media="all and (min-width: 1265px)" href="[css/page.css?d=202109070922](view-source:/css/page.css?d=202109070922)">`
So it adds a date to the link of the file so it's reloaded if you use a newer version.
I don't know if this works inside JS to load a JS and it's more work if you change a file.

**Comment by fichtner** [comment]
@Tragen yes we do have a similar construct:

https://github.com/opnsense/core/blob/821de0a9b1b461b144a1dc43d1450f38be201cb1/src/www/guiconfig.inc#L62

Need to look into how the JS files are imported by one another or if the page needs to define their presence anyway (best case).

**Comment by AdSchellevis** [comment]
@fichtner as far as I know you can't use similar trickery on js import statements. This likely needs to be taken care of on the server end (lighttpd)

**Comment by AdSchellevis** [comment]
@fichtner this https://github.com/opnsense/core/commit/314d975679afc9cf750a405c143495d551221b0a might help, but only for new cases.

**Comment by swhite2** [comment]
https://github.com/opnsense/core/commit/36560aa67933631eca5bf62a9af985b0809abfbc should make the imports cache safe
