### ISSUE TITLE
firmware: TODO list for for 24.7

### ISSUE THREAD

**Issue by fichtner** [opnsense/core#7525]
- [x] https://github.com/opnsense/tools/issues/399
- [x] create core.git/stable/24.7
- [x] create plugins.git/stable/24.7
- [x] what do do with duckdns migrations? d70c3714a1da9
- [x] sync ZFS installer code https://github.com/opnsense/installer/commit/5c84ae3386
- [x] https://github.com/opnsense/core/issues/7524
- [x] decide on https://github.com/opnsense/src/commit/18b8a9d5d3d https://github.com/opnsense/docs/pull/572 -- this is in RC1 but might be backed out for RC2
- [x] decide on infiniband changes https://github.com/opnsense/tools/issues/409 -- this is in RC1 but might be backed out for RC2
- [ ] https://github.com/opnsense/src/issues/207
